### ISSUE TITLE
Small GPL licence issue

### ISSUE THREAD

**Issue by siko1056** [gnu-octave/octave-websockets#1]
Thank you for your package :+1: 

While reviewing some metadata, I think there is a confusion between GPL 2 and 3.  The COPYING file is clearly the GPL2, but everywhere else the GPL 3 is written.

https://github.com/gnu-octave/octave-websockets/blob/449ad644d8b150c43f3e931f4bfb6fb22a82fb73/DESCRIPTION#L11

**Comment by MarcoMiretti** [comment]
Right, sorry for the confusion. Seems i forgot to update the license. I will upload the GPL v3 and update it.

**Comment by MarcoMiretti** [comment]
Done, thank you!
